doctrine:
    dbal:
        url: '%maindb_url%' #specificare connessione test
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
