#Consente di personalizzare servizi e ascolto di eventi in base all'installazione
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\Service\Integrazioni\Rfc249OutManagerSvc:
        tags:
            - { name: kernel.event_listener, event: Paziente.post_aggiorna_telefono, method: onPostAggiornaTelefono }
            - { name: kernel.event_listener, event: Paziente.post_aggiorna_residenza, method: onPostAggiornaResidenza }
